name: abflow_environment
channels:
  - conda-forge        # main scientific stack
  - defaults           # standard Anaconda channel
dependencies:
  # ────────────────── core interpreter ──────────────────
  - python=3.10
  - python_abi=3.10       # match the interpreter

  # ────────────────── open-force-field stack ─────────────
  - openff-toolkit=0.16.9
  - openmmforcefields=0.14.2

  # ────────────────── unchanged pins (no py312 builds) ───
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alchemlyb=2.4.1
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates          # let conda take the latest
  - contourpy=1.3.1
  # GPU / CUDA toolchain
  - cuda-version=12.8
  - cuda-cccl_linux-64=12.8.55
  - cuda-crt-dev_linux-64=12.8.61
  - cuda-crt-tools=12.8.61
  - cuda-cudart=12.8.57
  - cuda-cudart-dev_linux-64=12.8.57
  - cuda-cudart-static_linux-64=12.8.57
  - cuda-cudart_linux-64=12.8.57
  - cuda-cupti=12.8.57
  - cuda-cupti-dev=12.8.57
  - cuda-nvcc-tools=12.8.61
  - cuda-nvrtc=12.8.61
  - cuda-nvtx=12.8.55
  - cuda-nvvm-tools=12.8.61
  - cudnn=9.7.1.26
  - nccl=2.25.1.1
  # scientific python
  - cycler=0.12.1
  - fonttools=4.56.0
  - freetype=2.12.1
  - icu=75.1
  - importlib-metadata=8.6.1
  - jax=0.4.35
  - jaxlib=0.4.35           # conda will pick the CUDA-12 / py310 build
  - joblib=1.4.2
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - lcms2=2.17
  - libabseil=20240722.0
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.12.1
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgomp=14.2.0
  - libpng=1.6.47
  - libprotobuf=5.28.3
  - libsqlite=3.49.1
  - libxml2=2.13.6
  - loguru=0.7.2
  - lz4-c=1.10.0
  - matplotlib-base=3.10.0
  - ml_dtypes=0.5.1
  - ncurses=6.5
  - nglview=3.1.4
  - numexpr=2.10.2
  - numpy=2.2.3
  - openssl=3.4.1
  - opt-einsum=3.4.0
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.0.1
  - pyarrow=19.0.1
  - pyparsing=3.2.1
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=75.8.2
  - six
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tzdata                   # latest
  - unicodedata2=16.0.0
  - wheel
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zipp
  - zlib=1.3.1
  - zstd=1.5.7

  # ───────── optional extras (kept exactly as before) ─────────
  # remove these if you don't need CUDA-JAX:
  - pip
  - pip:
      - jax-cuda12-pjrt==0.4.35
      - jax-cuda12-plugin==0.4.35
      - pymbar==4.0.3

